--- # yaml ..
- hosts: slave
   remote_user: praveena92
   become: yes
   become_method: sudo
   connection: ssh
   gather_facts: yes
   vars:
      username: myuser
   tasks:
    - name: install httpd
	  yum:
	    name: httpd
            state: latest
    - name: making service start
	  service:
	    name: httpd
	    state: started
